### ISSUE TITLE
Automate the extraction of the RavenC binary version 

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#101]
For the moment it's hardcoded: https://github.com/CSHS-CWRA/RavenPy/blob/5090b7b9b16d83c0d5d2eaa7789dbd38fca8f140/ravenpy/config/rvs.py#L239

The best I guess would be to extract it dynamically from the binary itself.. but I'm not sure what is the best way to go with this, @Zeitsperre I'm sure you have ideas since you have been involved closely with related stuff!

**Comment by Zeitsperre** [comment]
Extracting it from the binary would be a bit of a strange process as it stands; The version is printed alongside a bunch of other information, so we would need to use regex on the stdout. This is made more complicated as the information waits for input before completing the process. I've asked for `--version` flag from @julemai that could serve this purpose for both `ostrich` and `ravenc`. **The version does not presently include the revision**; @cjauvin should we ask if it's possible to print both?

If we run directly off the `conda` package, we can try parsing it from the env. The `ravenc` and `ostrich` version and revision are joined, which would make this a bit easier. What do you think?

**Comment by huard** [comment]
https://github.com/CSHS-CWRA/RavenPy/blob/15ccc656fc93c7ff3fc7db5aed931754aa74eb61/ravenpy/models/base.py#L162

**Comment by Zeitsperre** [comment]
Wow! I had no idea that we could send additional input to a command line process. Considering that it's already written, this makes things much easier, haha. Would it make sense to pull that code out of there and into the `config` section? Determining the version feels like configuration code to me.

For the revision number, the decision to not join it to the version information has been made so the only place we can get it from is either the source code or from the version string that needs to be parsed from `conda list raven` (presently at `3.0.4.318). Once the official version of `raven` is made available, this won't be an issue. How important is the revision number?

**Comment by cjauvin** [comment]
I worry about our reliance on particular revision numbers, if we cannot somehow extract/log that information. From experience this will cause confusion and trouble eventually.

**Comment by Zeitsperre** [comment]
I think from the Slack discussion, the end goal is to drop the use of revision numbers. Once we have something that's packaged and meets all our versioning needs, we'll probably just start incrementing the versions with new feature integrations.

**Comment by cjauvin** [comment]
Let's close this I don't think it's relevant anymore.
