### ISSUE TITLE
Introduce the notion of "runs" in the file output folder structure

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#103]
The symptom is a warning that multiple files with the same name path are present in the output zip bundle.

The underlying problem is that we have no explicit notion of "multiple runs", which results in the reuse/rewrite of the same output folder when reusing the same model, like for instance here:

https://github.com/CSHS-CWRA/RavenPy/blob/9354e1b22799873e25a246d8cdd3a2db1cb3254d/ravenpy/utilities/forecasting.py#L175-L182

So the solution will be to add a notion of "run number" the the output folder structure, along with a counter which will need to be incremented every time `Raven.__call__` is called.

**Comment by richardarsenault** [comment]
@huard I think this is solved. Confirm?

**Comment by huard** [comment]
The new config solves this.
