### ISSUE TITLE
Add functionality to generate RV files that users can export through RavenPy

### ISSUE THREAD

**Issue by richardarsenault** [CSHS-CWRA/RavenPy#108]
In RavenWPS, we have the option to have the WPS server return the bundled rv files as a zip. Having this option exist explicitly in RavenPy would help a lot to simplify the model building process.

I'm thinking something like calling "model.export_rv" or something like this that will return a link to the rv files.

Perhaps this exists but I can't seem to find it!

Thanks

**Comment by richardarsenault** [comment]
I seem to have found the model.outputs['rv_config'] method, however on the pavics.ouranos.ca server it goes to a /tmp/ folder and I can't seem to download it. Any way we can make this available to the user?

**Comment by huard** [comment]
You can set the `workdir`, where all these files will be created. 

e.g. 
```
HMETS(workdir="./exp01")
```

**Comment by richardarsenault** [comment]
Thanks for the quick answer, and sorry for my delayed response. 

I tried this, and I get this error:

`model` = GR4JCN(workdir="./exp01")

`FileNotFoundError: [Errno 2] No such file or directory: PosixPath('exp01/exec/model/p00/raven'): PosixPath('exp01/exec/model/p00/raven')
`

**Comment by richardarsenault** [comment]
I should mention that it does create the folder in my writable-workspace parallel to the notebooks with the input files, but not the output files due to the error noted above.

**Comment by huard** [comment]
I can't reproduce this problem. On my end the directory is created and in the final subdirectory I can see the rv.zip file and download it. Reopen if problem occurs on your end.
