### ISSUE TITLE
Prevent careless tampering of RV member attributes

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#114]
Since it's too easy to make mistakes (i.e. setting `model.config.rvt.raincorrection` instead of `model.config.rvt.rain_correction`) I think it would be a good idea to prevent direct tampering with the variable members of the `config.rvs.RV` classes, either by either `__slots__` or by overriding `__setattr__` (see https://stackoverflow.com/questions/3603502/prevent-creating-new-attributes-outside-init).

**Comment by huard** [comment]
Done with pydantic.
