### ISSUE TITLE
Re-enable tests

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#16]
### Description
- Port https://github.com/Ouranosinc/raven/pull/322 here
- Use new functionality to download test files locally, replacing links in TESTDATA. 
- Confirm all tests pass

**Comment by huard** [comment]
@Zeitsperre Could you port your PR here and include a small example of how you think it should be used within the test suite ? 
@cjauvin I suggest we make this a fairly high priority. It's going to be dangerous to experiment with design ideas without the test suite running.

**Comment by Zeitsperre** [comment]
I'll start porting the tutorial utility once you've had a look at https://github.com/Ouranosinc/raven/pull/328

**Comment by Zeitsperre** [comment]
@huard @cjauvin 

Been working on this throughout this morning. One issue I'm coming up against is that we rely on globbing to access local files. Combining globbing with remote retrieval is a bit complicated. Here are some options:
- ~We use the PyGithub library to connect to the `raven-testdata` repo to get the filelist~ (terrible idea as it requires a user's GitHub token/access).
- We investigate the ease of using `urllib` or `Requests` to gather GitHub filelists (or make a new function using them to do this)
- We hardcode files typically globbed (some work, brittle)

Globbing returns strings, so I've already begun by modifying `get_file` to return lists of local file paths when given a sequence of strings. Are there other options to consider?

**Comment by huard** [comment]
If `get_file` accepted directory names, and in that case returned the list of files inside the directory, would that help ?

**Comment by cjauvin** [comment]
@Zeitsperre Not sure it's really relevant to the problem you mention but I'm taking a chance: I recently replaced globbing logic that Richard was using by this pattern, for reading a shapefile with Fiona:

https://github.com/Ouranosinc/raven/blob/wps_geomet/tests/test_ECCC_forecast.py#L24-L29

It's also easy to inspect the content of a zip package to determine the shapefile, without touching the disk.

**Comment by Zeitsperre** [comment]
> If `get_file` accepted directory names, and in that case returned the list of files inside the directory, would that help ?

In some cases, not all the files in a particular directory are used for as inputs for a given test (e.g. NetCDF -> xarray.dataset; rv* files -> Raven/Ostrich inputs), but If we had the file path list, the logic would be to glob that. I see what you're saying.

Would it make sense to create a `get_directory` function for this?

**Comment by Zeitsperre** [comment]
> @Zeitsperre Not sure it's really relevant to the problem you mention but I'm taking a chance: I recently replaced globbing logic that Richard was using by this pattern, for reading a shapefile with Fiona:
> 
> https://github.com/Ouranosinc/raven/blob/wps_geomet/tests/test_ECCC_forecast.py#L24-L29
> 
> It's also easy to inspect the content of a zip package to determine the shapefile, without touching the disk.

Not entirely relevant here but I might pick your brain for that on another project, because I can see the value!
