### ISSUE TITLE
Raven dates offset

### ISSUE THREAD

**Issue by richardarsenault** [CSHS-CWRA/RavenPy#164]
It would seem that Raven applies an offset to data in some instances, taking one day before the desired date when reading from a netcdf file. 
@huard has encountered this, perhaps more details would help pinpoint the issue.

**Comment by cjauvin** [comment]
Not sure about this one in particular, but a good place to discuss this kind of issue is the Raven Slack, with Julie and the others.

**Comment by richardarsenault** [comment]
Possible, I just wanted to leave a trace somewhere so we don't let it slip!

**Comment by huard** [comment]
To be clear, the offset is between the input forcing files and the output data saved by RavenC. An input marked with datetime x ends up being saved as an output with datetime x+1 day. This is not related to RavenPy, but to Raven itself, so not sure we want to keep this open here.
