### ISSUE TITLE
Auto-detect input variable units in netcdf and convert before running Raven

### ISSUE THREAD

**Issue by richardarsenault** [CSHS-CWRA/RavenPy#166]
Users that would like to use data sources such as ERA5 will get data in the original format, i.e. temperature in K and precipitation in meters. Raven will flag this as being too high (temps above 60°C), etc. 

Ideally, calling raven would be able to check the inputs for typical units such as K and m, and convert them to the required °C and mm.

**Comment by huard** [comment]
Would something like this do the job ?

```python
import pint
def gp(source, target):
    """Return linear transform parameters to convert one unit to another.

   If the target unit is given by `y = ax + b`, where `x` is the value of the source unit, then this function returns a, b. 

    Parameters
    ----------
    source : str
        Source unit string, pint-recognized. 
    target : str
        Target unit string, pint-recognized. 
    """
    b = pint.Quantity(0, source).to(target)
    a = pint.Quantity(1, source).to(target) - b
    return a.magnitude, b.magnitude

>>> gp(source="degK", target="degC")
(1.0, -273.15)
```
and then we can use the `:LinearTransform` command within `:DataCommand` to make the conversion. 

```python
>>> from ravenpy.config.commands import LinearTransform
>>> LinearTransform(*gp(source="degK", target="degC")).to_rv()
':LinearTransform 1.000000000000000 -273.149999999999977\n'
```
To recap, we need to note somewhere the units Raven expects (Table D.2 in the docs), extract the netCDF units, convert them to pint (`xclim.units.units2pint`), and create the linear transform.

**Comment by richardarsenault** [comment]
That could work yes. Just to be sure: This would be transparent to the user?
