### ISSUE TITLE
User interface refactoring discussion

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#167]
## Description

The PAVICS-Hydro workshop generated a lot of comments, some of them touching on the RavenPy interface. There are also a couple of open issues that suggest there might be problems with the "life-cycle" aspects of our interface. New requirements steming from the InfoCrue project also require some adjustments to the model configuration logic. 

I suggest we use this issue to explore ideas related to the RavenPy interface: 
* how emulators are configured
* how models are launched
* how results are exposed
* how models are "resumed" from an earlier experiment

### Why not include `ts` with all other model configuration parameters?

The input time series (ts) are handled separately from the model configuration, but there might be no real justification for this. 

### Is it confusing that running the model (`__call__`) does not return anything? 

Running the model changes the internal state of the Raven instance, but maybe it would be clearer if the return value was a "static" snapshot of the configuration and a `RavenOutput` instance?

Combining the two last suggestions, the workflow could be 
```python
config = GR4JCN(**config_params)
out = raven(config)
```

**Comment by richardarsenault** [comment]
This has been implemented
