### ISSUE TITLE
Get rid of annoying warnings due to non-existent state variables. 

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#216]
* RavenPy version: 0.8.1

### Description

RavenC complains when we initialize state variables that do not exist in the model. 
The `HRUStateVariableTableCommand.Record` includes all possible state variables, but some emulators don't use them, leading to warnings such as 
```
  /home/david/src/RavenPy/ravenpy/models/base.py:398: RavenWarning: Initial conditions specified for state variable not in model (CONV_STOR[97])
    warn(msg, category=RavenWarning)
```
When no state variables are set, maybe we could just leave the RVC blank.

**Comment by Zeitsperre** [comment]
This would be really great when running the testing suite. It's really annoying in its current state!
