### ISSUE TITLE
Support symbolic expressions in Raven configuration files

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#221]
### Description

If a model parameter is an expression calculated from the values of other parameters, we need to create extra configuration attributes and set their value within the `derived_parameters` method:
```
self.config.rvp.set_extra_attributes(
            one_minus_CEMANEIGE_X2=(1.0 - params.CEMANEIGE_X2)
        )
```

In Ostrich, we then need to create corresponding tied parameters
```
par_1_minus_x6 1 par_x6 linear -1.00 1.00 free
```

This is fine when there are few such parameters, but as we move to template more model properties (vegetation classes, land use classes, soil parameters), we expect an increase in the number of such derived parameters. An example is SoilParameterList, where we might have different types of soil using different fractions of the porosity. So one soil type would have POROSITY * 0.2, another POROSITY * 0.4, etc. In the current setup, we would need to manually created derived parameters for all of those. 

I propose to use symbolic expressions to encode those dependencies, then automatically compute the values using the symbolic logic.

**Comment by richardarsenault** [comment]
Implemented in Ravenpy
