### ISSUE TITLE
Changing params of a model doesn't change the end result

### ISSUE THREAD

**Issue by Mayetea** [CSHS-CWRA/RavenPy#249]
If you run a certain model with a set of parameters and you want to change these parameters to see their effects on the end result, the model won't change its values. The only way is to shutdown the kernel and reexecute. 

The issue was found while testing in the tutorial 04_Emulating_hydrological_models

**Comment by Zeitsperre** [comment]
Hello again! This is specifically a Jupyter-related problem, so if you could reopen this issue on https://github.com/Ouranosinc/raven, we can go from there!

**Comment by huard** [comment]
It could also be an xarray caching problem. 
Try changing the run_name before launching the second simulation to see if it solves the issue.

**Comment by huard** [comment]
The data is overwritten, but xarray doesn't realize it. Let's keep this open until we fix it.

**Comment by Mayetea** [comment]
Perfect, I'll close this one and open another one in the Ouranos repo, since it's not a backend issue. I'll also copy the discussion so we wont lose track of what was said here.
