### ISSUE TITLE
No observations line in hydrographs

### ISSUE THREAD

**Issue by Mayetea** [CSHS-CWRA/RavenPy#250]
In the tutorial 04_Emulating_hydrological_models, we test a GR4JCN model with some observations data, but in the graph, there's only the simulations values that are plot. It is then impossible to compare the simulation with the reality. 

![image](https://user-images.githubusercontent.com/22402751/211604133-a9e26caf-5fdf-43fd-b177-253a9c1ccdc7.png)

**Comment by Zeitsperre** [comment]
Hi @Mayetea, thanks for the issue!

As this is related specifically to the PAVICS service running Raven, I'm going to transfer this issue to https://github.com/Ouranosinc/raven. For issues relating to the notebook examples or to specific WPS services, please open those issues there.
