### ISSUE TITLE
Kernels automatically reopen if you refresh/open the browser for the open tabs

### ISSUE THREAD

**Issue by Mayetea** [CSHS-CWRA/RavenPy#251]
If you shut down all your kernels to save some space, but you don't close the tabs, then the reopening or refreshing (F5) of Ouranos will start a kernel for every opened tab. I'm pretty sure they don't use a lot of space since no execution are made, but they still must take some space. Since, the behavior is sneaky, many users may not be aware of this and a lot of unused kernels must be opened.

Before refreshing the browser:

![image](https://user-images.githubusercontent.com/22402751/211605436-8dcf93cc-58d0-4eed-a599-fcb645965ccf.png)

After reshing the browser :

![image](https://user-images.githubusercontent.com/22402751/211605634-81fbdcca-c7ed-476e-aa5d-edb0117a7262.png)

**Comment by huard** [comment]
This is known, but not a problem so far. We have a mechanism in place to kill inactive kernels after some period.
