### ISSUE TITLE
Drop cmdclass functions for building RavenC in setup.py

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenPy#261]
The `cmdclass` code based on setup.py is a bit clunky and difficult to maintain. This code is used for performing the C++ compiling of RavenC and Ostrich as an installation build step and, in the case of Anaconda installation, this code is often not even called.

It could also be argued that this code isn't even applicable to RavenPy as the use case for `cmdclass` build steps is for compiling and linking C++ libraries that offer Python objects/functions (like numpy; this is not the case for RavenC).

I would like to preserve the ability to compile RavenC and place it within the `PATH`, but only as a secondary CLI command. This could be performed by using the existing code with minimal effort.

**Comment by huard** [comment]
Sounds good. Agree that compiling should be deferred to conda.

**Comment by Zeitsperre** [comment]
Most of the code to perform the compiling is perfectly fine, applicable to any system that has GCC. I just want to pull it out of `setup.py` to make it much more maintanable.
