### ISSUE TITLE
Missing packages to run notebooks using fresh RavenPy install

### ISSUE THREAD

**Issue by richardarsenault** [CSHS-CWRA/RavenPy#272]
If users want to run ravenpy and notebooks "independently", such as to collect data from ERA5 or launch requests to the geoserver, they need to have some packages installed such as birdy, intake and others. Do we want to do this? Is this something that should come with a ravenpy install?

Because as of now, notebooks rely on being able to get data from geoserver, ERA5 using intake, etc.

**Comment by huard** [comment]
These dependencies should go in requirements_docs.txt
