### ISSUE TITLE
Alt Names for Gauge's model

### ISSUE THREAD

**Issue by Mayetea** [CSHS-CWRA/RavenPy#277]
In the new ravenpy configuration, the possibility to give an alternative name for an attribute doesn't work for latitude and longitude. I had to rename both attributes in my netCDF in order for the field to be recognize.

**Comment by huard** [comment]
This is used to extract the gauge coordinates, right ? Can you pass those as keyword arguments instead of trying to infer them from the nc?

the alt_names approach was designed for data variables, not coordinates, so the fix may not be obvious.

**Comment by huard** [comment]
I think I'll close this as a won't fix. The reasoning being that RavenPy assumes that you provide CF-compliant netCDF datasets, which normally would be interpretable with cf-xarray.
