### ISSUE TITLE
Having an elevation in the NC can cause issues

### ISSUE THREAD

**Issue by Mayetea** [CSHS-CWRA/RavenPy#279]
I extracted the data of a watershed from HYSETS_2020 and the resulting NC had an elevation of an xarray with 1 element. The method from_nc, crashes in the observationdata module, because it tries to get the value with [0] instead of item(0).

Removing the elevation from my NC and passing it in params, fixed the issue, but we shouldnt need to do this work around.

**Comment by huard** [comment]
Salut Francis, est-ce que tu te rappelles quel fichier était problématique?

**Comment by huard** [comment]
Laisse-faire, je pense pouvoir reproduire le problème que tu mentionnes.
