### ISSUE TITLE
OPeNDAP tests failing for Linux * PyPI builds

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenPy#299]
* RavenPy version: 0.12.2
* Python version: All
* Operating System: Linux

### Description

It appears that the `netcdf4-python` rebuild workaround is no longer working. This is negatively affecting many tests that rely on DAP protocols. Given that we rebuild the binaries from sources, the issue is likely not due to the packaging the `netcdf4` wheels.

### What I Did

`$ tox`

```python
...
=========================== short test summary info ============================
FAILED tests/test_emulators.py::test_canopex - OSError: [Errno -68] NetCDF: I/O failure: 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/ets/Watersheds_5797_cfcompliant.nc'
FAILED tests/test_external_dataset_access.py::TestGet::test_get_CASPAR_dataset - OSError: [Errno -68] NetCDF: I/O failure: 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/disk2/caspar/daily/GEPS_20180831.nc'
FAILED tests/test_utils.py::test_dap_specs - OSError: [Errno -68] NetCDF: I/O failure: 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/raven/raven-gr4j-cemaneige/Salmon-River-Near-Prince-George_meteo_daily.nc'
```

**Comment by Zeitsperre** [comment]
@tlvu could these errors have been due to the SSL certificate debacle?

**Comment by tlvu** [comment]
> @tlvu could these errors have been due to the SSL certificate debacle?

Probably not.  You opened this issue 2 weeks ago.  The SSL cert problem was only last Thu.  Is it possible to re-trigger the tests again to confirm?

**Comment by Zeitsperre** [comment]
Strangely, no. It doesn't seem reproducible now.

**Comment by tlvu** [comment]
> Strangely, no. It doesn't seem reproducible now.

So either that error is intermittent (if possible try 5-10 runs see if 1 fail) or it's some network errors on our Thredds side.

If still not reproducible after 10 runs I think we can just close this issue now.

**Comment by Zeitsperre** [comment]
Can't seem to make it happen. It must have been a network issue.
