### ISSUE TITLE
Move Raven python wrapper here

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#3]
### Description
The https://github.com/Ouranosinc/raven repo holds both the python wrapper for Raven and WPS processes. Moving the wrapper here would probably broaden usage and be easier to keep in sync with the Raven source code.

**Comment by Zeitsperre** [comment]
I imagine that most of the wrapping you allude to is in here? https://github.com/Ouranosinc/raven/blob/master/Makefile

**Comment by huard** [comment]
That's part of it, but the code is mostly in raven/models
