### ISSUE TITLE
Bias correction failure

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#322]
* RavenPy version: master
* Python version: 3.10
* Operating System: Ubuntu

### Description

Running the test suite with an updated xarray yields a failure:

```
FAILED tests/test_bias_correction.py::TestBiasCorrect::test_bias_correction - ValueError: dqm_adjust failed on block with coords : Coordinates:
```

**Comment by Zeitsperre** [comment]
Xclim version?

**Comment by huard** [comment]
0.45

**Comment by huard** [comment]
xarray: 2023.10.1

**Comment by huard** [comment]
I made a forced upgrade in my env, so this may be  just it.

**Comment by huard** [comment]
Downgrading to xarray 2023.1.0 solves the problem.
