### ISSUE TITLE
Allow users to override installing the `raven-hydro` dependency

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenPy#371]
The way that the requirements work right now, we absolutely need `raven-hydro` to be installed (either from PyPI/`pip` or via `conda`). Perhaps there could be a low-effort and safe approach to override this requirement for some special cases?

**Comment by Zeitsperre** [comment]
@julemai The issue is this line right here: https://github.com/CSHS-CWRA/RavenPy/blob/dbe5fbeee6305beda516968a6302786634b88fdc/tests/test_emulators.py#L7 We need the package installed to get the version string. I can maybe propose a fix this morning, but I don't have time to release something just yet.

**Comment by julemai** [comment]
Ahhhh. That makes sense. No worries regarding releasing anything right now. I'm happy to test it in case you do at one point.

**Comment by huard** [comment]
I'd be ok to just set the version string to "-" when the user provides her own executable.

**Comment by huard** [comment]
The offending line is in the tests, so I suspect that the code "should" work even if one test breaks.
