### ISSUE TITLE
Params is_symbolic failing on linux

### ISSUE THREAD

**Issue by TC-FF** [CSHS-CWRA/RavenPy#418]
### Setup Information

- ravenpy version: 0.16.0
- Python version: 3.12.7
- Operating System: Issue on WSL2 and linux cluster. Fine on windows

### Description

In config/rvs.py line 392 asdict(self.params) looses "Variable" : See screenshot below :
![dda6ff6d-ce85-4fa5-9809-e158302e1551](https://github.com/user-attachments/assets/c6839063-a9c5-469a-a621-5dbc246651ac)

So line 520 looking for Variable instances returns False and SpotSetup cannot initialize

On Windows, it's working fine :
![945c4461-0040-4340-80cc-8b46f77e1017](https://github.com/user-attachments/assets/8300e67e-20c4-4194-b88f-b9907c05f761)

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by huard** [comment]
Même version de python dans les deux cas ?

**Comment by huard** [comment]
Pourrais-tu essayer en remplaçant `asdict` par
```
from dataclasses import fields
...
params = {field.name: getattr(params, field.name) for field in fields(params)}
```

**Comment by TC-FF** [comment]
Super, 2 solutions de trouvé ! 
Soit en remplaçant la ligne :
`p = asdict(self.params)`
par 
`p = {field.name: getattr(self.params, field.name) for field in fields(self.params)}`

Soit en downgradant pymbolic à 2022.2 
Étrangement, j'ai pymbolic 2024.2 sur linux et 2022.2 sur Windows, pourtant dans deux environnement fait à partir du même yml
