### ISSUE TITLE
Refactor ravenpy.utils somewhere into ravenpy.utilities?

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#44]
I'm not sure it makes sense to have `ravenpy.utils` and `ravenpy.utilities`, shouldn't the former be moved to the latter?

**Comment by Zeitsperre** [comment]
There's a bunch of GIS stuff in there that should be moved. I certainly think it would be good to do, but we need to synchronize with RAVEN if we do. Could start doing it as soon as I'm done with https://github.com/CSHS-CWRA/RavenPy/pull/39
