### ISSUE TITLE
RTD docs is broken

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#58]
The current RTD docs for RavenPy is broken (some sections are missing, in particular the CLI section about Julie's grid weight script) seemingly because there are some dependency errors in the build process.

**Comment by Zeitsperre** [comment]
Looks like that's the case https://readthedocs.org/projects/ravenpy/builds/12991283/. I think we may need to ensure the docs fail on warnings so that we don't run into this problem suddenly.

I can look into this next week.

**Comment by tlvu** [comment]
> Looks like that's the case https://readthedocs.org/projects/ravenpy/builds/12991283/. I think we may need to ensure the docs fail on warnings so that we don't run into this problem suddenly.
> 
> I can look into this next week.

+1 on this.  Without fail on warnings, we've had silent doc build failure in the past and I have put in the fix for all the birds here https://github.com/bird-house/cookiecutter-birdhouse/pull/96

**Comment by cjauvin** [comment]
Great work @Zeitsperre this was epic!
