### ISSUE TITLE
Create "extract RVH data" script

### ISSUE THREAD

**Issue by cjauvin** [CSHS-CWRA/RavenPy#65]
I think it would make sense to create an RVH data extraction script (which would take as its input a Routing shapefile, and output an `.rvh` file) for RavenPy, similar to what we did with @julemai's grid weight generation logic:

https://github.com/CSHS-CWRA/RavenPy/blob/master/ravenpy/cli.py

This way, @dustming's Routing Toolkit could use that script, which would present the huge benefit that we stay DRY (which is very desirable especially for finicky extraction/conversion algos like these).

**Comment by cjauvin** [comment]
The way we would then use it:
```shell
$ ravenpy extract-rvh-data < routing_product.shp > toto.rvh
```

**Comment by julemai** [comment]
Hm. That sounds like a great idea but we would need a `extract-rvp-data` too, isn't it? Shall we do both in one command or two separate commands?

**Comment by dustming** [comment]
If this command will only be used by the Routing Toolkit, I won't suggest you do this. I guess I had to focus on my thesis in the following months (at least until September). And we can always implement this command when we begin to add RavenPy into the routing toolkit.  Of course, It would be another story, if this is a command that can be used by other applications :).
