### ISSUE TITLE
Revisit logic to specify Gauge latitude, longitude, elevation

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#75]
### Description

Parameters latitude, longitude, elevation are used in two commands: 
- Gauge
- HRU

At the moment, they are the same, but when we'll transition to HRU Command objects in the templates, Gauge commands will need to be provided with their own values. 

Note that these Gauge values don't seem to make any difference within our emulators, so unclear how critical this is.

**Comment by richardarsenault** [comment]
@huard Solved in new refactor?
