### ISSUE TITLE
Utilities to convert shapefiles to RavenPy-compatible dictionaries 

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenPy#8]
### Description

Assuming a shapefile containing multiple subbasins from https://zenodo.org/record/3667677#.X8EQpHWYVH4 is stored locally, convert the shapefile information into dictionaries that can then be used to instantiate routing relevant classes. 
See #7

**Comment by Zeitsperre** [comment]
Not sure if it's relevant, but this library might be handy for performing text-based format conversions: https://github.com/geomet/geomet

**Comment by huard** [comment]
Done with #30
