### ISSUE TITLE
Raven and Ostrich versions differ between `pip` and `conda`

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenPy#81]
* RavenPy version: 0.3.0
* Python version: any
* Operating System: any

### Description

ATTN @richardarsenault 

The `conda` packages present on `Anaconda` for `raven` and `ostrich` are not the same as those hard-coded with the `setup.py` here. For more information, see the `meta.yaml` recipes for them here: https://github.com/CSHS-CWRA/raven-feedstock/pull/3

The `ostrich` binary now points to a GitHub repo (!="Ostrich_2017-12-19_plus_progressJSON"):
```
git_url: https://github.com/usbr/ostrich.git
git_rev: v21.03.16
```
and `raven` is presently at a different revision (!="Raven-rev288"):
```
url: http://www.civil.uwaterloo.ca/jmai/raven/Raven-rev312.zip
```

Seeing as both methods do indeed work (albeit with some strange behaviour with the pip version) I think we should synchronise these versions, otherwise we'll have inconsistent behaviour.

**Comment by cjauvin** [comment]
@julemai
